version: '2'
services:
   db:
        image: postgres:15
        container_name: index_db
        restart: always
        environment:
                - POSTGRES_USER=odoo
                - POSTGRES_PASSWORD=hqd8^QDgh#WW
                - POSTGRES_DB=postgres
                - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
                - 51514:5432
        volumes:
                - db-data:/var/lib/postgresql/data/pgdata
   odoo:        
        image: dennokorir/tritel-index:15.0
        container_name: index_odoo
        restart: always
        ports:
                - 8015:8069
                - 8014:8072
        links:
                - db:db
        depends_on:
                - db
        volumes:
                - ./config:/etc/odoo
                - ./custom-addons:/mnt/extra-addons/custom-addons
                - odoo-data:/var/lib/odoo
volumes:
        odoo-data:
        db-data: